### ISSUE TITLE
JS Error in Chrome - can't see test results

### ISSUE THREAD

**Issue by Rosomack** [kncept/junit-reporter#5]
This happens when trying to view the test results in Chrome on my mac:

```
babel-5.8.34.js:3 Failed to load file:///Users/mikolaj.leszczynski/Documents/workspace/babylon-android/gateway/build/reports/tests/junit-platform/main.jsx: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
n.load @ babel-5.8.34.js:3
```
This results in just this text displaying:
```Loading Javascript

If this remains on the screen for more than a few seconds, something has gone wrong.
```

Firefox seems to work.

**Comment by nkrul** [comment]
Ah. This is because the project is currently using babel as a live transpiler in the browser, and is loading resources from the filesystem (file::) rather than a url (http:: / etc). It will work if you host it, or expose it on a build server.
I know how to fix it, its just a major change in how the .js is embedded. I'll get onto it.

**Comment by nkrul** [comment]
It will probably take a few hours before Maven Central is upated. You should be able to use v1.0.1 this afternoon.

**Comment by Rosomack** [comment]
Amazing, thanks so much for your help on both!
